const recommendationCards = [
    {
        color: 'yellow',
        label: 'images/like.svg',
        img: 'images/img2.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
    {
        color: 'yellow',
        label: 'images/like.svg',
        img: 'images/img3.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
    {
        color: 'yellow',
        label: 'images/like.svg',
        img: 'images/img4.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
    {
        color: 'yellow',
        label: 'images/like.svg',
        img: 'images/img1.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
    {
        color: 'yellow',
        label: 'images/like.svg',
        img: 'images/img2.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
    {
        color: 'yellow',
        label: 'images/like.svg',
        img: 'images/img3.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
    {
        color: 'yellow',
        label: 'images/like.svg',
        img: 'images/img4.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
    {
        color: 'yellow',
        label: 'images/like.svg',
        img: 'images/img1.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
];

