const saleCards = [
    {
        color: 'blue',
        label: '%',
        img: 'images/img1.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
    {
        color: 'blue',
        label: '%',
        img: 'images/img2.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
    {
        color: 'blue',
        label: '%',
        img: 'images/img3.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
    {
        color: 'blue',
        label: '%',
        img: 'images/img4.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
    {
        color: 'blue',
        label: '%',
        img: 'images/img1.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
    {
        color: 'blue',
        label: '%',
        img: 'images/img2.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
    {
        color: 'blue',
        label: '%',
        img: 'images/img3.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
    {
        color: 'blue',
        label: '%',
        img: 'images/img4.png',
        name: 'IP телефон Siemens Gigaset C530A IP',
        priceOnSale: '12 300 р.',
        price: '15 500 р.',
    },
];

